'use client';

import { useCallback, useEffect, useState } from 'react';

/**
 * DebugReportButton — fixed bottom-left button that opens a one-page
 * diagnostic report formatted to be photographed with a phone.
 *
 * Owner ask: "I click it and then it does everything you want or that will
 * be helpful and prints out a report that I can take a photo of with my
 * phone and share with you."
 *
 * The report is generated by /api/debug/report which aggregates: API health,
 * Ollama health, log tails (api/webui/ollama/install), `nvh status --deep --json`,
 * and pattern-matched suggestions. All probes fire in parallel from the
 * Next.js process which has the rootless filesystem access + child_process
 * to make this work even when FastAPI is dead.
 *
 * Visual design: monospace, high contrast, large enough text to read off a
 * phone photo, structured sections so a screenshot crop is still useful.
 */

interface LogTail {
  source: string;
  path: string;
  exists: boolean;
  sizeBytes: number;
  mtimeIso: string | null;
  lines: string[];
}

interface ServiceProbe {
  url: string;
  reachable: boolean;
  httpStatus: number | null;
  engineInitialized: boolean | null;
  body: string;
  error: string | null;
  elapsedMs: number;
}

interface DoctorResult {
  ran: boolean;
  format: 'json' | 'text' | 'error';
  binary: string;
  exitCode: number | null;
  report: unknown;
  stdout: string;
  stderr: string;
  elapsedMs: number;
}

interface DebugReport {
  generatedAt: string;
  env: {
    nvhHome: string;
    nvhBin: string | null;
    nvhLogs: string;
    nodeVersion: string;
    platform: string;
  };
  services: {
    api: ServiceProbe;
    ollama: ServiceProbe;
  };
  logs: LogTail[];
  doctor: DoctorResult;
  diagnostics: { label: string; hit: boolean; suggestion: string }[];
}

function formatReport(report: DebugReport, pageUrl: string): string {
  const lines: string[] = [];
  const pad = (s: string, n = 38) => s.padEnd(n, ' ');
  const bar = (ch = '=', n = 56) => ch.repeat(n);
  const sect = (title: string) => `\n--- ${title} ${'-'.repeat(Math.max(0, 56 - title.length - 5))}`;

  lines.push(bar());
  lines.push('  nvHive DEBUG REPORT');
  lines.push(bar());
  lines.push(`  Generated: ${report.generatedAt}`);
  lines.push(`  Page:      ${pageUrl}`);
  // 2026-06-10 audit: the header used to print NVH_HOME under the
  // "Node:" label — actively misleading on a report whose whole job is
  // being triaged from a (often header-cropped) phone photo. Each value
  // now sits under its own label; the ENV section below repeats them.
  lines.push(`  Platform:  ${report.env.platform}`);
  lines.push(`  NVH_HOME:  ${report.env.nvhHome}`);
  lines.push(`  Node:      ${report.env.nodeVersion}`);

  lines.push(sect('SUMMARY'));
  for (const h of report.diagnostics) {
    const icon = h.hit ? '[OK]' : '[!!]';
    lines.push(`  ${icon} ${h.label}`);
    if (!h.hit && h.suggestion) {
      lines.push(`       -> ${h.suggestion}`);
    }
  }

  lines.push(sect('SERVICES'));
  const api = report.services.api;
  lines.push(
    `  API    ${pad(api.reachable ? `HTTP ${api.httpStatus}` : 'unreachable', 14)}` +
      `engine_init=${api.engineInitialized === null ? '?' : api.engineInitialized}  ` +
      `(${api.elapsedMs}ms)`,
  );
  if (api.error) lines.push(`         error: ${api.error}`);
  const ol = report.services.ollama;
  lines.push(
    `  Ollama ${pad(ol.reachable ? `HTTP ${ol.httpStatus}` : 'unreachable', 14)}(${ol.elapsedMs}ms)`,
  );
  if (ol.error) lines.push(`         error: ${ol.error}`);

  lines.push(sect('ENV'));
  lines.push(`  NVH_HOME:   ${report.env.nvhHome}`);
  lines.push(`  NVH_LOGS:   ${report.env.nvhLogs}`);
  lines.push(`  NVH_BIN:    ${report.env.nvhBin || '(unset, falls through to PATH)'}`);
  lines.push(`  NodeJS:     ${report.env.nodeVersion}`);

  lines.push(sect('STATUS --DEEP'));
  lines.push(
    `  binary=${report.doctor.binary}  ran=${report.doctor.ran}  ` +
      `fmt=${report.doctor.format}  exit=${report.doctor.exitCode}  ` +
      `t=${report.doctor.elapsedMs}ms`,
  );
  if (report.doctor.format === 'json' && report.doctor.report) {
    const j = JSON.stringify(report.doctor.report, null, 2);
    // Cap to ~30 lines so the report stays photographable.
    const jLines = j.split('\n');
    lines.push(...jLines.slice(0, 30).map(l => `  ${l}`));
    if (jLines.length > 30) lines.push(`  ... (${jLines.length - 30} more lines truncated)`);
  } else if (report.doctor.stdout) {
    const stdoutLines = report.doctor.stdout.split('\n').slice(-20);
    lines.push(...stdoutLines.map(l => `  ${l}`));
  } else if (report.doctor.stderr) {
    lines.push(`  stderr: ${report.doctor.stderr.split('\n').slice(-10).join(' | ')}`);
  }

  for (const log of report.logs) {
    lines.push(sect(`LOG: ${log.source}`));
    lines.push(`  path: ${log.path}`);
    if (!log.exists) {
      lines.push('  (file does not exist yet)');
      continue;
    }
    lines.push(`  size: ${log.sizeBytes} bytes   mtime: ${log.mtimeIso}`);
    if (log.lines.length === 0) {
      lines.push('  (empty)');
    } else {
      const tail = log.lines.slice(-12);
      for (const l of tail) lines.push(`  ${l}`);
    }
  }

  lines.push('\n' + bar());
  lines.push('  END OF REPORT — share via screenshot or Copy to clipboard');
  lines.push(bar());

  return lines.join('\n');
}

export default function DebugReportButton() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<DebugReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [pageUrl, setPageUrl] = useState('');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setPageUrl(window.location.pathname + window.location.search);
    }
  }, [open]);

  // Esc-to-close — matches the footer hint.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  const generate = useCallback(async () => {
    setLoading(true);
    setError(null);
    setCopied(false);
    try {
      const r = await fetch('/api/debug/report', { cache: 'no-store' });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const data: DebugReport = await r.json();
      setReport(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  const openModal = useCallback(() => {
    setOpen(true);
    void generate();
  }, [generate]);

  const closeModal = useCallback(() => {
    setOpen(false);
  }, []);

  const copyToClipboard = useCallback(async () => {
    if (!report) return;
    const text = formatReport(report, pageUrl);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2_000);
    } catch {
      setError('clipboard write failed — select the text manually + copy');
    }
  }, [report, pageUrl]);

  const formatted = report ? formatReport(report, pageUrl) : '';

  return (
    <>
      {/* Bottom-left fixed button. Sits above the sidebar (which is z-40)
          but below modals (z-[100]+). Always visible, sized for touch + a
          phone camera to find. */}
      <button
        type="button"
        onClick={openModal}
        className="fixed left-3 bottom-3 z-[80] font-mono text-[11px] uppercase tracking-wider border rounded-sm shadow-lg"
        style={{
          background: '#7f1d1d',
          borderColor: '#fca5a5',
          color: '#fee2e2',
          padding: '8px 12px',
        }}
        title="Generate a debug report you can photograph + share"
        aria-label="Open debug report"
      >
        🩺 Debug Report
      </button>

      {open && (
        <div
          className="fixed inset-0 z-[110] flex items-center justify-center"
          style={{ background: 'rgba(0,0,0,0.7)' }}
          role="dialog"
          aria-modal="true"
          aria-label="nvHive debug report"
          onClick={(e) => {
            if (e.target === e.currentTarget) closeModal();
          }}
        >
          <div
            className="border rounded-sm flex flex-col"
            style={{
              background: '#0a0a0a',
              borderColor: '#3f3f46',
              color: '#fafafa',
              width: 'min(900px, 95vw)',
              height: 'min(80vh, 720px)',
            }}
          >
            {/* Header */}
            <div
              className="flex items-center gap-2 px-4 py-2 border-b font-mono text-[12px]"
              style={{ borderColor: '#3f3f46' }}
            >
              <span className="uppercase tracking-wider" style={{ color: '#76B900' }}>
                nvHive Debug Report
              </span>
              <span style={{ color: '#71717a' }}>
                {loading ? 'gathering…' : report ? 'ready' : error ? 'error' : 'idle'}
              </span>
              <div className="ml-auto flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => void generate()}
                  disabled={loading}
                  className="font-mono text-[10px] uppercase tracking-wider px-2 py-1 border rounded-sm disabled:opacity-40 hover:opacity-90"
                  style={{ borderColor: '#3f3f46' }}
                  title="Re-run the diagnostic"
                >
                  Re-run
                </button>
                <button
                  type="button"
                  onClick={() => void copyToClipboard()}
                  disabled={!report || loading}
                  className="font-mono text-[10px] uppercase tracking-wider px-2 py-1 border rounded-sm disabled:opacity-40 hover:opacity-90"
                  style={{
                    borderColor: '#3f3f46',
                    background: copied ? '#15803d' : 'transparent',
                  }}
                  title="Copy the report text to clipboard"
                >
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  type="button"
                  onClick={closeModal}
                  className="font-mono text-[10px] uppercase tracking-wider px-2 py-1 border rounded-sm hover:opacity-90"
                  style={{ borderColor: '#3f3f46' }}
                  aria-label="Close debug report"
                >
                  Close
                </button>
              </div>
            </div>

            {/* Body */}
            <div className="flex-1 overflow-auto p-3">
              {loading && (
                <div className="font-mono text-[12px] opacity-80">
                  Probing API + Ollama, tailing logs, running nvh status --deep…
                </div>
              )}
              {error && !loading && (
                <div className="font-mono text-[12px]" style={{ color: '#fca5a5' }}>
                  Could not gather report: {error}
                </div>
              )}
              {!loading && report && (
                <pre
                  className="font-mono text-[12px] leading-snug whitespace-pre-wrap break-words"
                  style={{ color: '#e4e4e7' }}
                  // Selectable for users who'd rather hand-copy than use the button.
                >
                  {formatted}
                </pre>
              )}
            </div>

            {/* Footer hint */}
            <div
              className="px-4 py-2 border-t font-mono text-[10px] opacity-80"
              style={{ borderColor: '#3f3f46' }}
            >
              Photograph the report or click <span style={{ color: '#76B900' }}>Copy</span> to share
              it. Press <span style={{ color: '#76B900' }}>Esc</span> or click outside to close.
            </div>
          </div>
        </div>
      )}
    </>
  );
}
