#!/usr/bin/env python
"""Regenerate docs/COMMANDS.md from the Typer registry.

    python scripts/gen_commands_doc.py          # rewrite docs/COMMANDS.md
    python scripts/gen_commands_doc.py --check  # exit 1 when the doc is stale

tests/test_commands_doc_parity.py runs the --check form, so a command added,
renamed or hidden without regenerating the doc fails CI.
"""

from __future__ import annotations

import sys
from pathlib import Path

import click
from typer.main import get_command

ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "COMMANDS.md"

# Help panels in display order; anything unlisted lands under "Other".
PANEL_ORDER = [
    "Core", "Query Modes", "Multi-Model", "Admin", "Infrastructure",
    "Media", "Subcommands", "Providers", "Other",
]
# Commands whose flags matter enough to list in full.
DETAILED = ("ask", "status", "do")


def _panel(cmd: click.Command) -> str:
    panel = getattr(cmd, "rich_help_panel", None)
    return panel if isinstance(panel, str) else "Other"


def _summary(cmd: click.Command) -> str:
    """First paragraph of the help text, collapsed to one line."""
    text = (cmd.help or "").strip()
    return " ".join(text.split("\n\n", 1)[0].split()).replace("|", "\\|")


def _subcommands(cmd: click.Command) -> dict[str, click.Command]:
    # Duck-typed: Typer's group class is not an isinstance() match for
    # click.Group under every Click release.
    return getattr(cmd, "commands", None) or {}


def _params(cmd: click.Command, kind: str) -> list[click.Parameter]:
    # ``param_type_name`` rather than isinstance(): Typer's Option/Argument
    # subclasses are not an isinstance() match under every Click release.
    return [p for p in cmd.params if p.param_type_name == kind]


def _usage(name: str, cmd: click.Command, prefix: str = "nvh") -> str:
    if _subcommands(cmd):
        return f"{prefix} {name} <command>"
    pieces = [
        p.name.upper() if p.required else f"[{p.name.upper()}]"
        for p in _params(cmd, "argument")
    ]
    return " ".join([prefix, name, *pieces]).strip()


def _table(rows: list[tuple[str, str]]) -> list[str]:
    out = ["| Command | Description |", "|---------|-------------|"]
    out.extend(f"| `{usage}` | {summary} |" for usage, summary in rows)
    return out


def _option_rows(cmd: click.Command) -> list[tuple[str, str]]:
    rows = []
    for param in _params(cmd, "option"):
        if getattr(param, "hidden", False) or "--help" in param.opts:
            continue
        flags = ", ".join([*param.opts, *param.secondary_opts])
        rows.append((flags, " ".join((param.help or "").split()).replace("|", "\\|")))
    return rows


def render(app=None) -> str:
    from nvh.cli.main import DEPRECATED_ALIASES

    if app is None:
        from nvh.cli.main import app as nvh_app

        app = nvh_app
    root = get_command(app)
    visible = {n: c for n, c in root.commands.items() if not c.hidden}
    hidden = {n: c for n, c in root.commands.items() if c.hidden}

    lines = [
        "# Commands",
        "",
        "<!-- Generated by scripts/gen_commands_doc.py from the Typer registry. Do not edit by hand. -->",
        "",
        "Complete reference for the `nvh` CLI. `nvh \"question\"` with no command",
        "routes the prompt to the best available advisor; `nvh` alone opens the REPL.",
        "A mistyped command prints a did-you-mean suggestion instead of being sent",
        "to an advisor, and a task-shaped bare prompt asks for an explicit `nvh do`.",
        "",
    ]

    by_panel: dict[str, list[tuple[str, str]]] = {}
    for name in sorted(visible):
        cmd = visible[name]
        by_panel.setdefault(_panel(cmd), []).append((_usage(name, cmd), _summary(cmd)))
    for panel in [*PANEL_ORDER, *sorted(set(by_panel) - set(PANEL_ORDER))]:
        if panel not in by_panel:
            continue
        lines += [f"## {panel}", "", *_table(by_panel[panel]), ""]

    lines += ["## Flags", ""]
    for name in DETAILED:
        cmd = visible.get(name)
        if cmd is None:
            continue
        lines += [f"### `{_usage(name, cmd)}`", "", "| Flag | Description |", "|------|-------------|"]
        lines += [f"| `{flags}` | {help_} |" for flags, help_ in _option_rows(cmd)]
        lines.append("")

    lines += ["## Command groups", ""]
    for name in sorted(n for n, c in visible.items() if _subcommands(c)):
        rows = []
        for sub_name, sub in sorted(_subcommands(visible[name]).items()):
            if sub.hidden:
                continue
            rows.append((_usage(sub_name, sub, prefix=f"nvh {name}"), _summary(sub)))
            rows.extend(
                (_usage(leaf_name, leaf, prefix=f"nvh {name} {sub_name}"), _summary(leaf))
                for leaf_name, leaf in sorted(_subcommands(sub).items())
                if not leaf.hidden
            )
        if rows:
            lines += [f"### `nvh {name}`", "", *_table(rows), ""]

    lines += [
        "## Deprecated spellings",
        "",
        "Hidden aliases kept for one release; each forwards to the command in its",
        "description. They do not appear in `nvh --help` and will be removed in 0.43.",
        "",
        # Only the DEPRECATED_ALIASES table: commands hidden for other reasons
        # (benchmark, the removed template group) are not deprecated spellings.
        *_table([(f"nvh {name}", _summary(hidden[name])) for name in sorted(DEPRECATED_ALIASES)]),
        "",
        "---",
        "",
        "Back to [README](../README.md)",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    sys.path.insert(0, str(ROOT))
    expected = render()
    if "--check" in argv:
        actual = DOC_PATH.read_text(encoding="utf-8").replace("\r\n", "\n") if DOC_PATH.exists() else ""
        if actual != expected:
            print(f"{DOC_PATH.relative_to(ROOT)} is stale — run: python scripts/gen_commands_doc.py", file=sys.stderr)
            return 1
        print(f"{DOC_PATH.relative_to(ROOT)} is current")
        return 0
    DOC_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {DOC_PATH.relative_to(ROOT)} ({len(expected.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
