"""Mock LLM provider — simulates responses without any API calls.

Use this for:
- Testing the full pipeline without spending money
- CI/CD pipelines
- Demos and onboarding before API keys are configured
"""

from __future__ import annotations

import asyncio
import random
import time
from collections.abc import AsyncIterator
from decimal import Decimal
from typing import Any

from nvh.providers.base import (
    CompletionResponse,
    FinishReason,
    HealthStatus,
    Message,
    ModelInfo,
    ProviderError,
    StreamChunk,
    Usage,
)

# ---------------------------------------------------------------------------
# Canned response templates
# ---------------------------------------------------------------------------

_CODE_TEMPLATE = """\
Here is a Python implementation:

```python
def solution(input_data):
    \"\"\"
    Processes the given input and returns a result.

    Args:
        input_data: The data to process.

    Returns:
        The processed result.
    \"\"\"
    # TODO: implement the actual logic
    result = input_data
    return result
```

This stub provides the correct function signature. Replace the body with your
actual implementation. Consider adding type hints and error handling as needed.
"""

_MATH_TEMPLATE = "The answer is 42. (More precisely: applying the relevant formula yields a result of 42, which satisfies the constraints of the problem.)"

_LOREM_TEMPLATE = """\
This is a simulated response from the Mock Provider regarding "{topic}". \
In a real deployment this text would be generated by a large language model based on the full context of your query. \
The mock provider is useful for verifying that the Council pipeline, routing, caching, and serialization all work correctly without consuming API credits. \
You can configure `latency_ms` to simulate network delays and `error_rate` to test your error-handling paths. \
When you are ready to use a real model, enable one of the configured providers in your `~/.council/config.yaml` file.
"""

_MODELS: list[ModelInfo] = [
    ModelInfo(
        model_id="mock/default",
        provider="mock",
        display_name="Mock Provider (Testing)",
        context_window=128000,
        max_output_tokens=4096,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        supports_json_mode=False,
        supports_system_prompt=True,
        input_cost_per_1m_tokens=Decimal("0"),
        output_cost_per_1m_tokens=Decimal("0"),
        typical_latency_ms=500,
        capability_scores={
            "code_generation": 0.5,
            "code_review": 0.5,
            "code_debug": 0.5,
            "reasoning": 0.5,
            "math": 0.5,
            "creative_writing": 0.5,
            "summarization": 0.5,
            "translation": 0.5,
            "conversation": 0.5,
            "question_answering": 0.5,
            "structured_extraction": 0.5,
            "multimodal": 0.5,
            "long_context_analysis": 0.5,
            "instruction_following": 0.5,
        },
        status="active",
    ),
    ModelInfo(
        model_id="mock/fast",
        provider="mock",
        display_name="Mock Provider Fast (Testing)",
        context_window=128000,
        max_output_tokens=4096,
        supports_streaming=True,
        input_cost_per_1m_tokens=Decimal("0"),
        output_cost_per_1m_tokens=Decimal("0"),
        typical_latency_ms=100,
        capability_scores={k: 0.5 for k in [
            "code_generation", "code_review", "code_debug", "reasoning", "math",
            "creative_writing", "summarization", "translation", "conversation",
            "question_answering", "structured_extraction", "multimodal",
            "long_context_analysis", "instruction_following",
        ]},
        status="active",
    ),
    ModelInfo(
        model_id="mock/slow",
        provider="mock",
        display_name="Mock Provider Slow (Testing)",
        context_window=128000,
        max_output_tokens=4096,
        supports_streaming=True,
        input_cost_per_1m_tokens=Decimal("0"),
        output_cost_per_1m_tokens=Decimal("0"),
        typical_latency_ms=2000,
        capability_scores={k: 0.5 for k in [
            "code_generation", "code_review", "code_debug", "reasoning", "math",
            "creative_writing", "summarization", "translation", "conversation",
            "question_answering", "structured_extraction", "multimodal",
            "long_context_analysis", "instruction_following",
        ]},
        status="active",
    ),
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _pick_response(messages: list[Message], prefix: str) -> str:
    """Choose a canned response based on the last user message content."""
    last_user = ""
    for msg in reversed(messages):
        if msg.role == "user":
            last_user = msg.content.lower()
            break

    # Detect category from keywords
    code_keywords = {"code", "function", "def ", "class ", "implement", "write a", "script", "program", "algorithm"}
    math_keywords = {"calculate", "compute", "solve", "equation", "integral", "derivative", "sum", "product", "math", "formula", "="}

    body: str
    if any(kw in last_user for kw in code_keywords):
        body = _CODE_TEMPLATE
    elif any(kw in last_user for kw in math_keywords):
        body = _MATH_TEMPLATE
    else:
        # Extract a short topic from the query (first 60 chars)
        topic = last_user[:60].strip() or "your query"
        body = _LOREM_TEMPLATE.format(topic=topic)

    return (prefix + body) if prefix else body


def _model_latency(model: str, base_ms: int) -> int:
    """Adjust latency based on model variant."""
    if "fast" in model:
        return max(50, base_ms // 5)
    if "slow" in model:
        return base_ms * 4
    return base_ms


# ---------------------------------------------------------------------------
# MockProvider
# ---------------------------------------------------------------------------

class MockProvider:
    """Simulates an LLM provider without making any real API calls."""

    def __init__(
        self,
        api_key: str = "",
        default_model: str = "mock/default",
        fallback_model: str = "mock/fast",
        base_url: str | None = None,
        provider_name: str = "mock",
        latency_ms: int = 500,
        error_rate: float = 0.0,
        response_prefix: str = "",
    ):
        self._default_model = default_model
        self._fallback_model = fallback_model
        self._provider_name = provider_name
        self._latency_ms = latency_ms
        self._error_rate = max(0.0, min(1.0, error_rate))
        self._response_prefix = response_prefix

    @property
    def name(self) -> str:
        return self._provider_name

    def _get_model(self, model: str | None) -> str:
        return model or self._default_model

    def _maybe_raise(self) -> None:
        """Raise a simulated error if error_rate > 0."""
        if self._error_rate > 0.0 and random.random() < self._error_rate:
            raise ProviderError(
                f"Simulated provider error (error_rate={self._error_rate:.0%})",
                provider=self._provider_name,
            )

    async def complete(
        self,
        messages: list[Message],
        model: str | None = None,
        temperature: float = 1.0,
        max_tokens: int = 4096,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> CompletionResponse:
        model_name = self._get_model(model)
        effective_latency = _model_latency(model_name, self._latency_ms)
        start = time.monotonic()

        self._maybe_raise()
        await asyncio.sleep(effective_latency / 1000.0)

        content = _pick_response(messages, self._response_prefix)
        elapsed = int((time.monotonic() - start) * 1000)

        # Estimate realistic token counts
        input_text = " ".join(m.content for m in messages)
        if system_prompt:
            input_text = system_prompt + " " + input_text
        in_tokens = self.estimate_tokens(input_text)
        out_tokens = self.estimate_tokens(content)

        return CompletionResponse(
            content=content,
            model=model_name,
            provider=self._provider_name,
            usage=Usage(
                input_tokens=in_tokens,
                output_tokens=out_tokens,
                total_tokens=in_tokens + out_tokens,
            ),
            cost_usd=Decimal("0"),
            latency_ms=elapsed,
            finish_reason=FinishReason.STOP,
        )

    async def stream(
        self,
        messages: list[Message],
        model: str | None = None,
        temperature: float = 1.0,
        max_tokens: int = 4096,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        model_name = self._get_model(model)
        effective_latency = _model_latency(model_name, self._latency_ms)

        self._maybe_raise()

        # Initial delay simulates network round-trip
        await asyncio.sleep(effective_latency / 1000.0 * 0.3)

        content = _pick_response(messages, self._response_prefix)
        words = content.split(" ")
        accumulated = ""

        input_text = " ".join(m.content for m in messages)
        if system_prompt:
            input_text = system_prompt + " " + input_text
        in_tokens = self.estimate_tokens(input_text)

        # Yield word-by-word with small inter-word delay
        inter_word_delay = max(0.01, (effective_latency / 1000.0 * 0.7) / max(len(words), 1))

        for i, word in enumerate(words):
            delta = word + (" " if i < len(words) - 1 else "")
            accumulated += delta
            is_final = i == len(words) - 1

            usage = None
            cost = None
            if is_final:
                out_tokens = self.estimate_tokens(accumulated)
                usage = Usage(
                    input_tokens=in_tokens,
                    output_tokens=out_tokens,
                    total_tokens=in_tokens + out_tokens,
                )
                cost = Decimal("0")

            yield StreamChunk(
                delta=delta,
                is_final=is_final,
                accumulated_content=accumulated,
                model=model_name,
                provider=self._provider_name,
                usage=usage,
                cost_usd=cost,
                finish_reason=FinishReason.STOP if is_final else None,
            )

            if not is_final:
                await asyncio.sleep(inter_word_delay)

    async def list_models(self) -> list[ModelInfo]:
        return list(_MODELS)

    async def health_check(self) -> HealthStatus:
        start = time.monotonic()
        await asyncio.sleep(self._latency_ms / 1000.0 * 0.1)
        elapsed = int((time.monotonic() - start) * 1000)
        return HealthStatus(
            provider=self._provider_name,
            healthy=True,
            latency_ms=elapsed,
            models_available=len(_MODELS),
        )

    def estimate_tokens(self, text: str) -> int:
        # ~4 chars per token is a reasonable approximation
        return max(1, len(text) // 4)
